### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by npacoder** [AnantDuhan/MERN-Ecommerce#6]
if (process.env.NODE_ENV === 'production') {
  res.status(err.statusCode).json({
    success: false,
    message: err.message,
  })
} else {
  res.status(err.statusCode).json({
    success: false,
    message: err.message,
    stack: err.stack
  })
}

**Comment by npacoder** [comment]
https://github.com/AnantDuhan/MERN-Ecommerce/blob/main/backend/middleware/error.js 

performance optimization:
use "else if" instead of "if" because we need to stop unnecessary "if" statements once the name or error code has been found.

**Comment by AnantDuhan** [comment]
Will Look into it for sure. Thanks
